version: '3.8'

services:
  config-server:
    build: ./microservice-config
    ports:
      - "8888:8888"
    networks:
      - microservices-network
    environment:
      - SPRING_PROFILES_ACTIVE=default
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8888/actuator/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

  eureka-server:
    build: ./microservice-eureka
    ports:
      - "8761:8761"
    depends_on:
      config-server:
        condition: service_healthy
    networks:
      - microservices-network
    environment:
      - SPRING_PROFILES_ACTIVE=default
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8761/actuator/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

  admin-db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: admindb
    ports:
      - "3306:3306"
    networks:
      - microservices-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5

  admin-service:
    build: ./microservice-admin
    ports:
      - "8097:8097"
    depends_on:
      eureka-server:
        condition: service_healthy
      admin-db:
        condition: service_healthy
    networks:
      - microservices-network
    environment:
      - SPRING_PROFILES_ACTIVE=default
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8097/actuator/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

  gateway:
    build: ./microservice-gateway
    ports:
      - "8080:8080"
    depends_on:
      eureka-server:
        condition: service_healthy
      admin-service:
        condition: service_healthy
    networks:
      - microservices-network
    environment:
      - SPRING_PROFILES_ACTIVE=default
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/actuator/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  microservices-network:
    driver: bridge
