version: '3.8'
services:
  config-server:
    build: ./microservice-config
    ports:
      - "8888:8888"
    networks:
      - microservices-network

  eureka-server:
    build: ./microservice-eureka
    ports:
      - "8761:8761"
    depends_on:
      - config-server
    networks:
      - microservices-network
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  gateway:
    build: ./microservice-gateway
    ports:
      - "8080:8080"
    depends_on:
      - eureka-server
    networks:
      - microservices-network

  patient-service:
    build: ./microservice-patient
    ports:
      - "8091:8091"
    depends_on:
      - eureka-server
    networks:
      - microservices-network

  doctor-service:
    build: ./microservice-doctor
    ports:
      - "8092:8092"
    depends_on:
      - eureka-server
    networks:
      - microservices-network

  appointment-service:
    build: ./microservice-appointment
    ports:
      - "8093:8093"
    depends_on:
      - eureka-server
    networks:
      - microservices-network

  billing-service:
    build: ./microservice-billing
    ports:
      - "8094:8094"
    depends_on:
      - eureka-server
    networks:
      - microservices-network

  medicalrecord-service:
    build: ./microservice-medicalrecord
    ports:
      - "8095:8095"
    depends_on:
      - eureka-server
    networks:
      - microservices-network

  notification-service:
    build: ./microservice-notification
    ports:
      - "8096:8096"
    depends_on:
      - eureka-server
    networks:
      - microservices-network

  admin-service:
    build: ./microservice-admin
    ports:
      - "8097:8097"
    depends_on:
      - eureka-server
    networks:
      - microservices-network

networks:
  microservices-network:
    driver: bridge