spring:
  application:
    name: admin-service

  cloud:
    config:
      uri: http://config-server:8888
      fail-fast: true

  config:
    import: "optional:configserver:"

server:
  port: 8097

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

