spring:
  application:
    name: eureka-server

  cloud:
    config:
      uri: http://config-server:8888
      fail-fast: true

  config:
    import: "optional:configserver:"

server:
  port: 8761

eureka:
  instance:
    hostname: eureka-server

  client:
    register-with-eureka: false
    fetch-registry: false
