spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/RickUbb/MedicalManagementSystem.git
          search-paths: microservice-config/src/main/resources/configurations
          default-label: pruebas
server:
  port: 8888
