server:
  port: 8080

spring:
  application:
    name: msvc-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: admins
          uri: http://localhost:8097
          predicates:
            - Path=/api/v1/admins/**
        - id: appointments
          uri: http://localhost:8093
          predicates:
            - Path=/api/v1/appointments/**
        - id: billings
          uri: http://localhost:8094
          predicates:
            - Path=/api/v1/bills/**
        - id: doctors
          uri: http://localhost:8092
          predicates:
            - Path=/api/v1/doctors/**
        - id: medicalRecords
          uri: http://localhost:8095
          predicates:
            - Path=/api/v1/medical-record/**
        - id: notifications
          uri: http://localhost:8096
          predicates:
            - Path=/api/v1/notifications/**
        - id: patients
          uri: http://localhost:8091
          predicates:
            - Path=/api/v1/patients/**