server:
  port: 8080

spring:
  application:
    name: msvs-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: admins
          uri: http://localhost:8097
          predicates:
            - Path=/api/v1/admins/**

