spring:
  application:
    name: gateway

  cloud:
    config:
      uri: http://config-server:8888
      fail-fast: true

  config:
    import: "optional:configserver:"

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

  instance:
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 30

