spring:
  application:
    name: msvc-gateway
  config:
    import: optional:configserver:http://config-server:8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
